### ISSUE TITLE
Alterar o tema através do banco

### ISSUE THREAD

**Issue by multiarts** [maestriam/samurai#1]
Primeiro o parabenizo pelo package.

Achei super fácil de usar, mas estou pensando na possibilidade de fazer a alteração dinamicamente, ter uma table "themes" e quando o sistema estiver on já ir buscar qual está ativo e gravar em um cookie para não ficar consultando o BD.

Pois o cliente final pode querer alterar o tema e não tem acesso ao terminal para digitar o comando ```php artisan samurai:use```.

**Comment by giusampaio** [comment]
Olá @multiarts, muito obrigado por usar o samurai e pelo seu retorno. De verdade, seu retorno é muito importante pra mim. 

"Achei super fácil de usar". Esse era o objetivo principal do pacote. Já vi alguns outros pacotes trabalhavam com temas no Laravel, mas nenhum que fosse utilizada de maneira simples como eu queria. Fico feliz de ter esse objetivo alcançado. 

Em relação a sua sugestão, ela até já está em desenvolvimento. Na próxima versão do pacote, o sistema terá uma facade chamado Samurai, onde você pode utilizar todas as funcionalidades que tem no artisan, além de poder pegar todos os temas instalados no sistema, qual o tema atual, verificar se um tema ou diretiva já existe, etc.  E dando spoilers, estou melhorando a parte para instalar temas via composer, que atualmente já faz mas não tá bem explicito ali.

Espero acabar isso em breve e atualizar a documentação para poder disponibilizar para vocês. 

Muito obrigado pelo seu feedback. Até a próxima! :}

**Comment by multiarts** [comment]
@giusampaio estou estudando todo o pack, espero contribuir mais e crescer este pack, aguardando atualizações. rsrs
Até logo.
